name: CI

on: push

env:
  CODECOV_TOKEN: 827161c5-c165-4ff3-85fb-384a115a96e1

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: cache
        id: packages
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            ./packages/*/dist
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/packages/{core,testing}/**/*.ts') }}
          restore-keys: ${{ runner.os }}-yarn-
      
      - name: install
        if: steps.packages.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile --non-interactive
          yarn workspace @bluish/core build
          yarn workspace @bluish/testing build

  lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: [install]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: cache
        id: packages
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            ./packages/*/dist
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/packages/{core,testing}/**/*.ts') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: lint
        run: yarn eslint .

  testing:
    runs-on: ubuntu-latest
    needs: [install]
    name: Testing
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: cache
        id: packages
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            ./packages/*/dist
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/packages/{core,testing}/**/*.ts') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: jest
        run: yarn jest --coverage --ci

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./coverage
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
